# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('1', 'Молоко'), ('2', 'Сыр'), ('3', 'Йогурт'), ('4', 'Кефир'), ('5', 'Творог')], max_length=1, verbose_name='Категория')),
                ('volume', models.PositiveIntegerField(verbose_name='Объём/Вес ед. упаковки, мл/гр')),
                ('pack', models.CharField(choices=[('1', 'ПЭТ'), ('2', 'пластиковый конт.'), ('3', 'пластиковый стакан запайка / крышка'), ('4', 'Кусок, вакуум')], max_length=1, verbose_name='Тип упаковки')),
                ('expiration', models.PositiveIntegerField(verbose_name='Срок годности (сут.)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
