# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Молоко'), ('2', 'Сыр'), ('3', 'Йогурт'), ('4', 'Кефир'), ('5', 'Творог')], default='', max_length=1, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
