# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default='2017-01-01', verbose_name='Дата доставки'),
            preserve_default=False,
        ),
    ]
