# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171108_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Молоко'), ('2', 'Сыр'), ('3', 'Йогурт'), ('4', 'Кефир'), ('5', 'Творог'), ('6', 'Йогурт греческий')], max_length=1, verbose_name='Категория'),
        ),
    ]
